name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job de calidad de código
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci

    - name: Run ESLint
      run: |
        cd backend && npm run lint
        cd ../frontend && npm run lint

    - name: Run Prettier check
      run: |
        cd backend && npm run format:check
        cd ../frontend && npm run format:check

    - name: Run tests with coverage
      run: |
        cd backend && npm run test:cov
        cd ../frontend && npm run test:cov

    - name: SonarQube Scan
      uses: sonarqube-community/sonarqube-scan-action@v2.0.1
      if: env.SONAR_TOKEN != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=prospecter-fichap
          -Dsonar.sources=backend/src,frontend/src
          -Dsonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
          -Dsonar.coverage.exclusions=**/*.test.js,**/*.spec.js,**/test/**,**/tests/**,**/*.test.ts,**/*.spec.ts

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          backend/coverage/
          frontend/coverage/

    - name: Upload Snyk report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: snyk-report
        path: snyk.sarif

    - name: Upload Semgrep report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: semgrep-report
        path: semgrep.sarif

    - name: Generate coverage badge
      if: always()
      run: |
        cd backend && npx coverage-badges-cli --output coverage/badge.svg || echo "Badge generation failed"

    - name: Upload coverage badge
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: backend/coverage/badge.svg

  # Job de testing
  test:
    name: Test
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: prospecter_fichap_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd backend && npm ci
        cd ../frontend && npm ci

    - name: Run backend tests
      run: |
        cd backend
        npm run test:cov
      env:
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
        DATABASE_NAME: prospecter_fichap_test
        DATABASE_USER: postgres
        DATABASE_PASSWORD: password
        REDIS_HOST: localhost
        REDIS_PORT: 6379

    - name: Run frontend tests
      run: |
        cd frontend
        npm run test:cov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./backend/coverage/lcov.info,./frontend/coverage/lcov.info
        flags: backend,frontend
        name: codecov-umbrella
        token: ${{ secrets.CODECOV_TOKEN }}

  # Job de security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://localhost:3000'
        rules_file_name: '.zap/rules.tsv'
        cmd_options: '-a'

  # Job de build y push de imágenes
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    needs: [code-quality, test, security]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      if: env.DOCKER_USERNAME != '' && env.DOCKER_REGISTRY_TOKEN != ''
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Job de deployment a staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to staging server
      uses: appleboy/ssh-action@v1.0.3
      if: env.STAGING_HOST != '' && env.STAGING_USER != '' && env.STAGING_SSH_KEY != ''
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USER }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: |
          cd /opt/prospecter-fichap
          git pull origin main
          docker-compose pull
          docker-compose up -d --remove-orphans
          docker system prune -f

    - name: Run smoke tests
      if: env.STAGING_HOST != ''
      run: |
        sleep 30
        curl -f http://${{ secrets.STAGING_HOST }}/health || exit 1

    - name: Notify Slack on success
      uses: 8398a7/action-slack@v3
      if: success() && env.SLACK_WEBHOOK_URL != ''
      with:
        status: success
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: '✅ Deploy to staging successful!'

    - name: Notify Slack on failure
      uses: 8398a7/action-slack@v3
      if: failure() && env.SLACK_WEBHOOK_URL != ''
      with:
        status: failure
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        text: '❌ Deploy to staging failed!'

  # Job de performance testing
  performance:
    name: Performance Test
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install k6
      run: |
        wget https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz
        tar -xzf k6-v0.47.0-linux-amd64.tar.gz
        sudo cp k6-v0.47.0-linux-amd64/k6 /usr/local/bin/
        k6 version

    - name: Run performance tests
      run: |
        if [ -f "performance/load-test.js" ]; then
          k6 run --out json=performance-results.json performance/load-test.js
        else
          echo "Performance test file not found, skipping..."
        fi

    - name: Upload performance results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: performance-results
        path: performance-results.json 