name: Snyk Security
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v3
        if: env.SNYK_TOKEN != ''
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Build Docker images for scanning
        if: env.SNYK_TOKEN != ''
        run: |
          docker build -t prospecter-fichap-backend:latest ./backend
          docker build -t prospecter-fichap-frontend:latest ./frontend
      
      - name: Run Snyk to check backend Docker image
        uses: snyk/actions/docker@v3
        if: env.SNYK_TOKEN != ''
        with:
          image: prospecter-fichap-backend:latest
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      - name: Run Snyk to check frontend Docker image
        uses: snyk/actions/docker@v3
        if: env.SNYK_TOKEN != ''
        with:
          image: prospecter-fichap-frontend:latest
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} 